#version 430

layout( local_size_x = 32 ) in;

layout( push_constant ) uniform params {
  uint len;
} PushConstant;

layout(std430, binding = 0) buffer a 
{
    double arr[];
};

layout(std430, binding = 1) buffer b
{
    double conv[];
};

void main() 
{
    uint idx = gl_GlobalInvocationID.x;
    double sum = 0.;
    for(int i = -3; i < 4; ++i)
    {
        sum += arr[idx + i];
    }
    conv[idx] = arr[idx] - sum / 7.;
}